Fix attribute error for slack reader
This reference wasn't updated since the latest change and broke the reader with:
AttributeError: 'SlackReader' object has no attribute 'client'. Did you mean: '_client'?