fix: Remove `cache_dir` Pydantic field validation
Error trace
```
ValidationError: 1 validation error for GaudiEmbedding
cache_folder
  Field required [type=missing, input_value={'embed_batch_size': 10, ...text_instruction': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/missing
```