fix direct reranker use in bm25_retriever example
postprocess_nodes expects List[NodeWithScore], was given List[TextNode]

error was -
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[35], line 6
      1 from llama_index.core import QueryBundle
      3 retrieved_nodes = hybrid_retriever.retrieve(
      4     "What is the impact of climate change on the ocean?"
      5 )
----> 6 reranked_nodes = reranker.postprocess_nodes(
      7     nodes,
      8     query_bundle=QueryBundle(
      9         "What is the impact of climate change on the ocean?"
     10     ),
     11 )
     13 print("Initial retrieval: ", len(retrieved_nodes), " nodes")
     14 print("Re-ranked retrieval: ", len(reranked_nodes), " nodes")

File .../llama_index/core/postprocessor/types.py:55, in BaseNodePostprocessor.postprocess_nodes(self, nodes, query_bundle, query_str)
     53 else:
     54     pass
---> 55 return self._postprocess_nodes(nodes, query_bundle)

File .../llama_index/core/postprocessor/sbert_rerank.py:64, in SentenceTransformerRerank._postprocess_nodes(self, nodes, query_bundle)
     61 if len(nodes) == 0:
     62     return []
---> 64 query_and_nodes = [
...
     79     },
     80 ) as event:
     81     scores = self._model.predict(query_and_nodes)
AttributeError: 'TextNode' object has no attribute 'node'