returning existing response and handling validation error of StructuredRefineResponse
Fixing below error -:

pydantic.error_wrappers.ValidationError: 2 validation errors for StructuredRefineResponse
answer
  field required (type=value_error.missing)
query_satisfied
  field required (type=value_error.missing)
[{'source': ''}, {'source': ''}]