[nebula graph] trim backticks from nebulagraph queries
It seems that backticks are being passed into nebulagraph directly, which is raising
errors. I'm not sure how far up the chain these backticks are being added in,
but in trying to find where to fix it I got scared of breaking other graph stores.

So, here is a quick solution to strip out backticks from these queries.

Below is an example of the error this fixes:

```
ERROR:llama_index.graph_stores.nebulagraph:Query failed. Query: ```
MATCH (p:`entity`)-[:relationship]->(m:`entity`) WHERE p.`entity`.`name` == 'Chris Pratt'
RETURN p.`entity`.`name`;
```, Param: {}Error message: Query failed. Query: ```
MATCH (p:`entity`)-[:relationship]->(m:`entity`) WHERE p.`entity`.`name` == 'Chris Pratt'
RETURN p.`entity`.`name`;
```, Param: {}Error message: SyntaxError: syntax error near ```
MATCH'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/root/volume/llama_index/graph_stores/nebulagraph.py", line 213, in execute
    raise e
  File "/root/volume/llama_index/graph_stores/nebulagraph.py", line 189, in execute
    raise ValueError(
ValueError: Query failed. Query: ```
MATCH (p:`entity`)-[:relationship]->(m:`entity`) WHERE p.`entity`.`name` == 'Chris Pratt'
RETURN p.`entity`.`name`;
```, Param: {}Error message: SyntaxError: syntax error near ```
MATCH'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/volume/examples/######/prompt.py", line 67, in <module>
    response = query_engine.query(
  File "/root/volume/llama_index/indices/query/base.py", line 23, in query
    response = self._query(str_or_query_bundle)
  File "/root/volume/llama_index/query_engine/knowledge_graph_query_engine.py", line 203, in _query
    graph_store_response = self.graph_store.query(query=graph_store_query)
  File "/root/volume/llama_index/graph_stores/nebulagraph.py", line 545, in query
    result = self.execute(query, param_map)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f2c00487e20 state=finished raised ValueError>]
```